---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Demo: News Manager Showcase"
subtitle: "NestJS, AngularJS, Keycloak & PostgresSQL"
logo: "assets/icons/logo.png"

header: true
footer: '<p>Created with ❤️ by <a href="https://www.alfonsoprado.com">Alfonso Prado</a> for the community using various open-source technologies. Contact me at <a href="mailto:contact@alfonsoprado.com">contact@alfonsoprado.com</a></p>'

theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
message:
  style: "is-link" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "Welcome to the demo!"
  icon: "fa fa-grin"
  content: "This administration panel for the News Manager project provides quick and convenient access to the different technologies used in the project. From this panel, administrators can manage the backend and frontend of the News Manager, as well as access graphical user interface (GUI) to manage PostgreSQL database through PgAdmin4. Additionally, administrators can also access Keycloak, an enterprise-grade identity and access management solution, directly from the panel."

links:
  - name: "Github"
    icon: "fab fa-github"
    url: "https://github.com/alfonsoprado"
    target: "_blank" 
  - name: "Personal website"
    icon: "fas fa-globe"
    url: "https://alfonsoprado.com"
    target: "_blank"
  - name: "Contact"
    icon: "fas fa-envelope"
    url: "mailto:contact@alfonsoprado.com"

services:
  - name: "Demo"
    icon: "fas fa-rocket"
    items:
      # - name: "Angular"
      #   logo: "assets/tools/frontend.png"
      #   subtitle: "User Interface Development"
      #   tag: "frontend"
      #   keywords: "frontend"
      #   url: "http://localhost:10000"
      - name: "Nestjs"
        logo: "assets/tools/backend.png"
        subtitle: "Server-Side Application Development"
        tag: "backend"
        keywords: "backend"
        url: "http://localhost:10001"
  - name: "Databases"
    icon: "fas fa-database"
    items:
      - name: "PostgreSQL"
        logo: "assets/tools/postgresql.png"
        subtitle: "Relational database management"
        tag: "postgresql"
        keywords: "postgresql sql"
        url: "http://localhost:10002/browser/"  
  - name: "Applications"
    icon: "fas fa-cloud"
    items:
      - name: "Docker"
        logo: "assets/tools/docker.png"
        subtitle: "Containers"
        keywords: "docker"
        tag: "docker"
        url: "http://localhost:10004"   
      - name: "Fakesmtp"
        logo: "assets/tools/email.png"
        subtitle: "Fake SMTP server"
        keywords: "fakesmtp"
        tag: "fakesmtp"
        url: "http://localhost:10003"

